name: mindheal
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0


dependencies:
  flutter:
    sdk: flutter

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8


  # Utility Packages
  url_launcher: ^6.3.1
  intl: 0.19.0
  connectivity_plus: ^6.1.3
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.17
  lottie: ^3.3.1
  shimmer: ^3.0.0
  flutter_native_splash: ^2.4.0
  logger: ^2.5.0
  smooth_page_indicator: ^1.2.0+3
  country_code_picker: ^3.1.0







  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Firebase
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  firebase_messaging: ^15.2.2
  cloud_firestore: ^5.6.3
  firebase_storage: ^12.4.2
  cloud_functions: ^5.3.4

  # Notification
  flutter_local_notifications: ^19.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/logos/
    - assets/images/content/
    - assets/images/animations/
    - assets/images/on_boarding_images/

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
